### ISSUE TITLE
.env sample

### ISSUE THREAD

**Issue by jeredb** [tomasienrbc/notes#3]
It would be awesome for self hosting

**Comment by tomasienrbc** [comment]
All you need for local is: 
APP_ENV="local"

If you want to deploy
APP_ENV="production"
REMOTE_HOST='111.111.11.11'
REMOTE_ROOT='/var/www'
REMOTE_PROJECT='blankslate.io'
REMOTE_USER='youruser'
REMOTE_PUBLIC_KEYPHRASE='yourpassword'
REMOTE_PUBLIC_KEY='path/to/your/public/key'

**Comment by clarkbarz** [comment]
An example .env file has been added to repository and the README has been updated to include .env instructions when setting up the project locally.
